<div class="text-center">
    <h1 class="text-shadow no-margin text-white text-4x p-v-lg">
      <span class="text-2x font-bold m-t-lg block">Disculpame</span>
    </h1>
    <img src="<?php echo $staticHost ?>/img/cloud.png"/>
    <p class="h4 m-v-lg text-u-c font-bold">No pude procesar tu solicitud. ¿Estás seguro que es la ruta correcta?</p>
    <div class="p-v-lg">
      Gracias!
    </div>
</div>