<div class="row">
		<div class="span12">
			<form method="post" action="<?php echo $baseHost ?>/login" class="form-horizontal">
			  <fieldset>
			    <div id="legend">
			      <legend class="">Login</legend>
			    </div>
			    <div class="control-group">
			      <!-- Username -->
			      <label for="username" class="control-label">Username</label>
			      <div class="controls">
			        <input type="text" class="input-xlarge" placeholder="" name="name" id="username">
			      </div>
			    </div>
			    <div class="control-group">
			      <!-- Password-->
			      <label for="password" class="control-label">Password</label>
			      <div class="controls">
			        <input type="password" class="input-xlarge" placeholder="" name="password" id="password">
			      </div>
			    </div>
			    <div class="control-group">
			      <!-- Button -->
			      <div class="controls">
			        <button class="btn btn-success">Login</button>
			      </div>
			    </div>
			  </fieldset>
			</form>
		</div>
	</div>